export type GiftCardPartnerGroup = { category: string; brands: readonly string[] };

/** Supplied 2026 Engage2Reward/GiftCard Partners directory; names are not a promise of current inventory. */
export const giftCardPartnerGroups: readonly GiftCardPartnerGroup[] = [
  { category: "Automotive", brands: [
    "AutoZone®",
    "Jiffy Lube®",
    "Turo",
  ] },
  { category: "Babies & Kids", brands: [
    "Baby Depot at Burlington",
    "babyGap",
    "Babylist",
    "Build-A-Bear Workshop®",
    "Carter’s",
    "OshKosh B'gosh",
    "Skip Hop",
    "The Children’s Place",
  ] },
  { category: "Charity", brands: [
    "Charity Choice",
    "Charity On Top – Disaster Relief",
  ] },
  { category: "Clothing & Accessories", brands: [
    "Abercrombie & Fitch",
    "Adidas",
    "Aerie®",
    "Aeropostale",
    "Allbirds",
    "American Eagle®",
    "ASOS",
    "Athleta",
    "Banana Republic",
    "Belk",
    "Bloomingdale's",
    "Burlington",
    "Chico’s",
    "Chubbies",
    "DSW",
    "Gap",
    "Gap Options",
    "GO Shop",
    "H&M",
    "Hanna Andersson",
    "Hollister",
    "Kohl's",
    "L.L. Bean",
    "Lands’ End®",
    "Lane Bryant",
    "LOFT",
    "Lucky Brand",
    "Macy's",
    "Marshalls",
    "Nautica",
    "Nordstrom",
    "Nordstrom Rack",
    "Old Navy",
    "Sierra Trading Post",
    "Skechers",
    "Soma",
    "Sunglass Hut",
    "T.J.Maxx",
    "thredUP",
    "Tommy Bahama",
    "Under Armour®",
    "UNTUCKit",
    "White House Black Market",
    "Zappos.com",
  ] },
  { category: "Grocery, Convenience, Pharmacy & Gas", brands: [
    "Acme Market",
    "Albertsons Companies",
    "Albertsons Everyday",
    "Albertsons From the Heart",
    "Andronico’s",
    "Balducci’s",
    "BP",
    "Carrs",
    "CVS®",
    "Haggen",
    "Jewel-Osco",
    "Kings",
    "Kroger",
    "Lucky",
    "Meijer",
    "Pavilions",
    "Pilot Flying J",
    "Publix",
    "Randalls",
    "Safeway",
    "Shaw’s",
    "Sheetz",
    "Speedway",
    "Star Market",
    "Tom Thumb",
    "Vons",
    "Walgreens",
  ] },
  { category: "Delivery Services", brands: [
    "1-800-Baskets.com",
    "1-800-Flowers.com",
    "Cheryl's Cookies",
    "DoorDash",
    "GrubHub",
    "Home Chef",
    "Instacart",
    "Lobster Gram",
    "Omaha Steaks®",
    "Shari’s Berries",
    "Stitch Fix®",
    "The Popcorn Factory",
    "Uber Eats®",
  ] },
  { category: "Digital & Gaming", brands: [
    "EA Origin Apex",
    "Gamestop®",
    "Google Play",
    "IMVU",
    "Jagex Runescape",
    "Meta Quest",
    "NetDragon",
    "Nexon Karma Koin",
    "Nintendo",
    "Perfect World Entertainment",
    "Pirate101™",
    "Razer Gold",
    "Roblox",
    "Sony PlayStation",
    "Twitch",
    "VALORANT",
    "Wizard101™",
    "XBOX",
    "XBOX Game Pass Essential",
    "XBOX Game Pass Ultimate",
  ] },
  { category: "Electronics", brands: [
    "Crutchfield®",
    "Microsoft Office 365 Home",
    "P.C. Richard and Son",
  ] },
  { category: "Cryptocurrency", brands: [
    "Bitjem",
  ] },
  { category: "Entertainment", brands: [
    "AMC Theaters",
    "Bowlero",
    "Cinemark",
    "Dave & Buster's",
    "Fandango",
    "GCodes® AT&T Prepaid Plans",
    "GCodes® Global Retail",
    "Hulu",
    "Main Event",
    "Paramount+",
    "Regal",
    "SiriusXM",
    "Sling TV",
    "TIDAL",
    "Vudu",
  ] },
  { category: "Experiences", brands: [
    "Global Experiences Card Powered by Viator",
    "Go Play Golf by Fairway Rewards",
    "Great American Days",
    "iFLY",
    "StubHub",
    "TopGolf",
  ] },
  { category: "Food & Restaurants", brands: [
    "99 Restaurant & Pubs",
    "Applebee’s",
    "Arby’s",
    "Aquarium",
    "Auntie Anne’s – Mix It Up®",
    "Babin’s Seafood House",
    "Bahama Breeze®",
    "Bakers Square",
    "Baja Fresh",
    "Baskin-Robbins",
    "Benihana",
    "Bertucci's®",
    "Bill’s Bar & Burger",
    "Black Angus Steakhouse",
    "Blaze Pizza",
    "Blimpie®",
    "Bloomin’ Brands",
    "Bob Evans Restaurants®",
    "Bonefish Grill",
    "Brinker International",
    "Bubba Gump",
    "Buffalo Wild Wings®",
    "Burger King",
    "Cadillac Bar",
    "California Pizza Kitchen",
    "Carrabba's",
    "Carvel – Mix It Up®",
    "Chart House",
    "Chili's® Grill & Bar",
    "Chipotle",
    "Cinnabon – Mix It Up®",
    "Cold Stone Creamery",
    "Cracker Barrel",
    "Darden Restaurants",
    "Dickey’s BBQ",
    "Dos Caminos",
    "Duck Donuts",
    "Dunkin’",
    "Dutch Bros Coffee®",
    "Famous Dave’s®",
    "FIVE GUYS®",
    "Fleming's",
    "Fogo de Chao Brazilian Steakhouse",
    "GO Eat",
    "GO Enjoy",
    "Grotto",
    "Hard Rock Café",
    "Harry & David",
    "Hooters",
    "IHOP®",
    "Jamba Juice®",
    "Jersey Mike’s Subs",
    "Jimmy John’s",
    "Kentucky Fried Chicken",
    "Krispy Kreme",
    "LaGriglia",
    "Landry’s",
    "Landry’s Seafood",
    "Lazy Dog",
    "Legal Sea Foods",
    "Logan’s Roadhouse®",
    "Longhorn Steakhouse®",
    "Maggiano's Little Italy®",
    "McAlister’s Deli – Mix It Up®",
    "McCormick & Schmick’s",
    "McDonald’s",
    "Mitchell’s Fish Market",
    "Mix It Up™",
    "Moe’s Southwest Grill – Mix It Up®",
    "Modern Market",
    "Morton’s Steakhouse",
    "O'Charley's",
    "Olive Garden",
    "On The Border",
    "Outback Steakhouse",
    "P.F. Chang's",
    "Panda Express",
    "Panera Bread",
    "Papa John’s",
    "Peet’s Coffee & Tea",
    "Piccadilly",
    "Pinkberry®",
    "Qdoba Mexican Eats",
    "Rainforest Café",
    "Red Lobster®",
    "Red Robin®",
    "River Crab Blue Water Inn",
    "Rubio’s Coastal Grill",
    "Ruby Tuesday",
    "Ruth’s Chris Steak House",
    "Saltgrass Steak House",
    "Schlotsky’s – Mix It Up®",
    "Seasons 52®",
    "Smashburger",
    "Smoothie King",
    "SONIC®",
    "Starbucks",
    "Steak 'n Shake®",
    "Strip House",
    "Subway®",
    "sweetFrog®",
    "Taco Bell®",
    "Texas Roadhouse",
    "TGI Fridays®",
    "The Cheesecake Factory",
    "The Coffee Bean & Tea Leaf®",
    "The Oceanaire",
    "Tower of the Americas",
    "UNO Pizzeria & Grill®",
    "Vic & Anthony’s",
    "Village Inn",
    "Willie G's",
    "Yard House®",
    "Zaxby’s",
  ] },
  { category: "General Merchandise", brands: [
    "Amazon",
    "Sam's Club",
    "Target",
    "The Engage2Reward™ Choice Card",
    "Walmart",
    "Walmart (Alcohol / Tobacco / Firearms Prohibited)",
    "Walmart Healthy Living",
  ] },
  { category: "Home Furnishings & Improvement", brands: [
    "Ace Hardware",
    "Bed Bath & Beyond",
    "Canvaspop",
    "CB2",
    "Cost Plus World Market®",
    "Crate & Barrel",
    "HomeGoods",
    "IKEA",
    "Lowe’s®",
    "Menards®",
    "Pottery Barn®",
    "The Container Store",
    "The Home Depot®",
    "Wayfair",
    "west elm®",
    "Williams Sonoma®",
  ] },
  { category: "Pets", brands: [
    "1-800-PetSupplies.com",
    "BarkBox",
    "Chewy®",
    "Pets Choice Card",
    "Petco",
    "PetSmart",
  ] },
  { category: "Specialty Retail", brands: [
    "Apple Gift Card",
    "Barnes & Noble",
    "Bath & Body Works",
    "Best Buy®",
    "eBay",
    "Etsy",
    "Fanatics",
    "Fruit Bouquets",
    "Groupon",
    "Guitar Center",
    "LUSH Fresh Handmade Cosmetics",
    "Michaels",
    "Office Depot® Office Max®",
    "Sephora",
    "Spa Week",
    "Staples",
    "The Vitamin Shoppe®",
    "Total Wine & More",
    "Tractor Supply Company",
    "Ulta",
    "Yankee Candle®",
  ] },
  { category: "Sporting Goods", brands: [
    "Academy Sports + Outdoors",
    "Bass Pro Shops®",
    "Cabela’s®",
    "Callaway",
    "Columbia",
    "DICK's Sporting Goods",
    "MLB Shop",
    "NASCAR.com",
    "NBA Store",
    "NFLShop.com",
    "NHL Shop",
    "PXG",
    "REI",
    "Sportsman’s Warehouse",
  ] },
  { category: "Travel & Entertainment", brands: [
    "AirBnB",
    "Amtrak",
    "Best Western",
    "Carnival Cruise Lines",
    "Celebrity Cruises",
    "Delta Airlines",
    "Disney Parks/Stores",
    "Fairmont Hotels & Resorts",
    "Global Hotel Card Powered by Expedia",
    "Golden Nugget",
    "Holland America Line",
    "Hotels.com®",
    "Marriott",
    "Princess Cruise Lines",
    "Raffles Hotels & Resorts",
    "Royal Caribbean",
    "San Luis Resort",
    "Southwest® Airlines",
    "TripGift®",
    "Swissôtel Hotels & Resorts",
    "Turo",
    "Ube",
  ] },
];
