-- Supplied Engage2Reward/GiftCard Partners directory, kept separate from active offers.
-- A directory name does not imply current inventory, denomination, or fulfillment approval.
-- Idempotent because this additive directory was first installed through the dashboard SQL editor.
begin;

create table if not exists public.gift_card_partner_brands (
  provider_category text not null,
  brand_name text not null,
  created_at timestamptz not null default now(),
  primary key (provider_category, brand_name)
);

alter table public.gift_card_partner_brands enable row level security;
do $$ begin
  if not exists (select 1 from pg_policies where schemaname = 'public'
    and tablename = 'gift_card_partner_brands' and policyname = 'Public can read gift card partner directory') then
    create policy "Public can read gift card partner directory"
      on public.gift_card_partner_brands for select to anon, authenticated using (true);
  end if;
end $$;
grant select on public.gift_card_partner_brands to anon, authenticated;

insert into public.gift_card_partner_brands (provider_category, brand_name) values
  ('Automotive', 'AutoZone®'),
  ('Automotive', 'Jiffy Lube®'),
  ('Automotive', 'Turo'),
  ('Babies & Kids', 'Baby Depot at Burlington'),
  ('Babies & Kids', 'babyGap'),
  ('Babies & Kids', 'Babylist'),
  ('Babies & Kids', 'Build-A-Bear Workshop®'),
  ('Babies & Kids', 'Carter’s'),
  ('Babies & Kids', 'OshKosh B''gosh'),
  ('Babies & Kids', 'Skip Hop'),
  ('Babies & Kids', 'The Children’s Place'),
  ('Charity', 'Charity Choice'),
  ('Charity', 'Charity On Top – Disaster Relief'),
  ('Clothing & Accessories', 'Abercrombie & Fitch'),
  ('Clothing & Accessories', 'Adidas'),
  ('Clothing & Accessories', 'Aerie®'),
  ('Clothing & Accessories', 'Aeropostale'),
  ('Clothing & Accessories', 'Allbirds'),
  ('Clothing & Accessories', 'American Eagle®'),
  ('Clothing & Accessories', 'ASOS'),
  ('Clothing & Accessories', 'Athleta'),
  ('Clothing & Accessories', 'Banana Republic'),
  ('Clothing & Accessories', 'Belk'),
  ('Clothing & Accessories', 'Bloomingdale''s'),
  ('Clothing & Accessories', 'Burlington'),
  ('Clothing & Accessories', 'Chico’s'),
  ('Clothing & Accessories', 'Chubbies'),
  ('Clothing & Accessories', 'DSW'),
  ('Clothing & Accessories', 'Gap'),
  ('Clothing & Accessories', 'Gap Options'),
  ('Clothing & Accessories', 'GO Shop'),
  ('Clothing & Accessories', 'H&M'),
  ('Clothing & Accessories', 'Hanna Andersson'),
  ('Clothing & Accessories', 'Hollister'),
  ('Clothing & Accessories', 'Kohl''s'),
  ('Clothing & Accessories', 'L.L. Bean'),
  ('Clothing & Accessories', 'Lands’ End®'),
  ('Clothing & Accessories', 'Lane Bryant'),
  ('Clothing & Accessories', 'LOFT'),
  ('Clothing & Accessories', 'Lucky Brand'),
  ('Clothing & Accessories', 'Macy''s'),
  ('Clothing & Accessories', 'Marshalls'),
  ('Clothing & Accessories', 'Nautica'),
  ('Clothing & Accessories', 'Nordstrom'),
  ('Clothing & Accessories', 'Nordstrom Rack'),
  ('Clothing & Accessories', 'Old Navy'),
  ('Clothing & Accessories', 'Sierra Trading Post'),
  ('Clothing & Accessories', 'Skechers'),
  ('Clothing & Accessories', 'Soma'),
  ('Clothing & Accessories', 'Sunglass Hut'),
  ('Clothing & Accessories', 'T.J.Maxx'),
  ('Clothing & Accessories', 'thredUP'),
  ('Clothing & Accessories', 'Tommy Bahama'),
  ('Clothing & Accessories', 'Under Armour®'),
  ('Clothing & Accessories', 'UNTUCKit'),
  ('Clothing & Accessories', 'White House Black Market'),
  ('Clothing & Accessories', 'Zappos.com'),
  ('Grocery, Convenience, Pharmacy & Gas', 'Acme Market'),
  ('Grocery, Convenience, Pharmacy & Gas', 'Albertsons Companies'),
  ('Grocery, Convenience, Pharmacy & Gas', 'Albertsons Everyday'),
  ('Grocery, Convenience, Pharmacy & Gas', 'Albertsons From the Heart'),
  ('Grocery, Convenience, Pharmacy & Gas', 'Andronico’s'),
  ('Grocery, Convenience, Pharmacy & Gas', 'Balducci’s'),
  ('Grocery, Convenience, Pharmacy & Gas', 'BP'),
  ('Grocery, Convenience, Pharmacy & Gas', 'Carrs'),
  ('Grocery, Convenience, Pharmacy & Gas', 'CVS®'),
  ('Grocery, Convenience, Pharmacy & Gas', 'Haggen'),
  ('Grocery, Convenience, Pharmacy & Gas', 'Jewel-Osco'),
  ('Grocery, Convenience, Pharmacy & Gas', 'Kings'),
  ('Grocery, Convenience, Pharmacy & Gas', 'Kroger'),
  ('Grocery, Convenience, Pharmacy & Gas', 'Lucky'),
  ('Grocery, Convenience, Pharmacy & Gas', 'Meijer'),
  ('Grocery, Convenience, Pharmacy & Gas', 'Pavilions'),
  ('Grocery, Convenience, Pharmacy & Gas', 'Pilot Flying J'),
  ('Grocery, Convenience, Pharmacy & Gas', 'Publix'),
  ('Grocery, Convenience, Pharmacy & Gas', 'Randalls'),
  ('Grocery, Convenience, Pharmacy & Gas', 'Safeway'),
  ('Grocery, Convenience, Pharmacy & Gas', 'Shaw’s'),
  ('Grocery, Convenience, Pharmacy & Gas', 'Sheetz'),
  ('Grocery, Convenience, Pharmacy & Gas', 'Speedway'),
  ('Grocery, Convenience, Pharmacy & Gas', 'Star Market'),
  ('Grocery, Convenience, Pharmacy & Gas', 'Tom Thumb'),
  ('Grocery, Convenience, Pharmacy & Gas', 'Vons'),
  ('Grocery, Convenience, Pharmacy & Gas', 'Walgreens'),
  ('Delivery Services', '1-800-Baskets.com'),
  ('Delivery Services', '1-800-Flowers.com'),
  ('Delivery Services', 'Cheryl''s Cookies'),
  ('Delivery Services', 'DoorDash'),
  ('Delivery Services', 'GrubHub'),
  ('Delivery Services', 'Home Chef'),
  ('Delivery Services', 'Instacart'),
  ('Delivery Services', 'Lobster Gram'),
  ('Delivery Services', 'Omaha Steaks®'),
  ('Delivery Services', 'Shari’s Berries'),
  ('Delivery Services', 'Stitch Fix®'),
  ('Delivery Services', 'The Popcorn Factory'),
  ('Delivery Services', 'Uber Eats®'),
  ('Digital & Gaming', 'EA Origin Apex'),
  ('Digital & Gaming', 'Gamestop®'),
  ('Digital & Gaming', 'Google Play'),
  ('Digital & Gaming', 'IMVU'),
  ('Digital & Gaming', 'Jagex Runescape'),
  ('Digital & Gaming', 'Meta Quest'),
  ('Digital & Gaming', 'NetDragon'),
  ('Digital & Gaming', 'Nexon Karma Koin'),
  ('Digital & Gaming', 'Nintendo'),
  ('Digital & Gaming', 'Perfect World Entertainment'),
  ('Digital & Gaming', 'Pirate101™'),
  ('Digital & Gaming', 'Razer Gold'),
  ('Digital & Gaming', 'Roblox'),
  ('Digital & Gaming', 'Sony PlayStation'),
  ('Digital & Gaming', 'Twitch'),
  ('Digital & Gaming', 'VALORANT'),
  ('Digital & Gaming', 'Wizard101™'),
  ('Digital & Gaming', 'XBOX'),
  ('Digital & Gaming', 'XBOX Game Pass Essential'),
  ('Digital & Gaming', 'XBOX Game Pass Ultimate'),
  ('Electronics', 'Crutchfield®'),
  ('Electronics', 'Microsoft Office 365 Home'),
  ('Electronics', 'P.C. Richard and Son'),
  ('Cryptocurrency', 'Bitjem'),
  ('Entertainment', 'AMC Theaters'),
  ('Entertainment', 'Bowlero'),
  ('Entertainment', 'Cinemark'),
  ('Entertainment', 'Dave & Buster''s'),
  ('Entertainment', 'Fandango'),
  ('Entertainment', 'GCodes® AT&T Prepaid Plans'),
  ('Entertainment', 'GCodes® Global Retail'),
  ('Entertainment', 'Hulu'),
  ('Entertainment', 'Main Event'),
  ('Entertainment', 'Paramount+'),
  ('Entertainment', 'Regal'),
  ('Entertainment', 'SiriusXM'),
  ('Entertainment', 'Sling TV'),
  ('Entertainment', 'TIDAL'),
  ('Entertainment', 'Vudu'),
  ('Experiences', 'Global Experiences Card Powered by Viator'),
  ('Experiences', 'Go Play Golf by Fairway Rewards'),
  ('Experiences', 'Great American Days'),
  ('Experiences', 'iFLY'),
  ('Experiences', 'StubHub'),
  ('Experiences', 'TopGolf'),
  ('Food & Restaurants', '99 Restaurant & Pubs'),
  ('Food & Restaurants', 'Applebee’s'),
  ('Food & Restaurants', 'Arby’s'),
  ('Food & Restaurants', 'Aquarium'),
  ('Food & Restaurants', 'Auntie Anne’s – Mix It Up®'),
  ('Food & Restaurants', 'Babin’s Seafood House'),
  ('Food & Restaurants', 'Bahama Breeze®'),
  ('Food & Restaurants', 'Bakers Square'),
  ('Food & Restaurants', 'Baja Fresh'),
  ('Food & Restaurants', 'Baskin-Robbins'),
  ('Food & Restaurants', 'Benihana'),
  ('Food & Restaurants', 'Bertucci''s®'),
  ('Food & Restaurants', 'Bill’s Bar & Burger'),
  ('Food & Restaurants', 'Black Angus Steakhouse'),
  ('Food & Restaurants', 'Blaze Pizza'),
  ('Food & Restaurants', 'Blimpie®'),
  ('Food & Restaurants', 'Bloomin’ Brands'),
  ('Food & Restaurants', 'Bob Evans Restaurants®'),
  ('Food & Restaurants', 'Bonefish Grill'),
  ('Food & Restaurants', 'Brinker International'),
  ('Food & Restaurants', 'Bubba Gump'),
  ('Food & Restaurants', 'Buffalo Wild Wings®'),
  ('Food & Restaurants', 'Burger King'),
  ('Food & Restaurants', 'Cadillac Bar'),
  ('Food & Restaurants', 'California Pizza Kitchen'),
  ('Food & Restaurants', 'Carrabba''s'),
  ('Food & Restaurants', 'Carvel – Mix It Up®'),
  ('Food & Restaurants', 'Chart House'),
  ('Food & Restaurants', 'Chili''s® Grill & Bar'),
  ('Food & Restaurants', 'Chipotle'),
  ('Food & Restaurants', 'Cinnabon – Mix It Up®'),
  ('Food & Restaurants', 'Cold Stone Creamery'),
  ('Food & Restaurants', 'Cracker Barrel'),
  ('Food & Restaurants', 'Darden Restaurants'),
  ('Food & Restaurants', 'Dickey’s BBQ'),
  ('Food & Restaurants', 'Dos Caminos'),
  ('Food & Restaurants', 'Duck Donuts'),
  ('Food & Restaurants', 'Dunkin’'),
  ('Food & Restaurants', 'Dutch Bros Coffee®'),
  ('Food & Restaurants', 'Famous Dave’s®'),
  ('Food & Restaurants', 'FIVE GUYS®'),
  ('Food & Restaurants', 'Fleming''s'),
  ('Food & Restaurants', 'Fogo de Chao Brazilian Steakhouse'),
  ('Food & Restaurants', 'GO Eat'),
  ('Food & Restaurants', 'GO Enjoy'),
  ('Food & Restaurants', 'Grotto'),
  ('Food & Restaurants', 'Hard Rock Café'),
  ('Food & Restaurants', 'Harry & David'),
  ('Food & Restaurants', 'Hooters'),
  ('Food & Restaurants', 'IHOP®'),
  ('Food & Restaurants', 'Jamba Juice®'),
  ('Food & Restaurants', 'Jersey Mike’s Subs'),
  ('Food & Restaurants', 'Jimmy John’s'),
  ('Food & Restaurants', 'Kentucky Fried Chicken'),
  ('Food & Restaurants', 'Krispy Kreme'),
  ('Food & Restaurants', 'LaGriglia'),
  ('Food & Restaurants', 'Landry’s'),
  ('Food & Restaurants', 'Landry’s Seafood'),
  ('Food & Restaurants', 'Lazy Dog'),
  ('Food & Restaurants', 'Legal Sea Foods'),
  ('Food & Restaurants', 'Logan’s Roadhouse®'),
  ('Food & Restaurants', 'Longhorn Steakhouse®'),
  ('Food & Restaurants', 'Maggiano''s Little Italy®'),
  ('Food & Restaurants', 'McAlister’s Deli – Mix It Up®'),
  ('Food & Restaurants', 'McCormick & Schmick’s'),
  ('Food & Restaurants', 'McDonald’s'),
  ('Food & Restaurants', 'Mitchell’s Fish Market'),
  ('Food & Restaurants', 'Mix It Up™'),
  ('Food & Restaurants', 'Moe’s Southwest Grill – Mix It Up®'),
  ('Food & Restaurants', 'Modern Market'),
  ('Food & Restaurants', 'Morton’s Steakhouse'),
  ('Food & Restaurants', 'O''Charley''s'),
  ('Food & Restaurants', 'Olive Garden'),
  ('Food & Restaurants', 'On The Border'),
  ('Food & Restaurants', 'Outback Steakhouse'),
  ('Food & Restaurants', 'P.F. Chang''s'),
  ('Food & Restaurants', 'Panda Express'),
  ('Food & Restaurants', 'Panera Bread'),
  ('Food & Restaurants', 'Papa John’s'),
  ('Food & Restaurants', 'Peet’s Coffee & Tea'),
  ('Food & Restaurants', 'Piccadilly'),
  ('Food & Restaurants', 'Pinkberry®'),
  ('Food & Restaurants', 'Qdoba Mexican Eats'),
  ('Food & Restaurants', 'Rainforest Café'),
  ('Food & Restaurants', 'Red Lobster®'),
  ('Food & Restaurants', 'Red Robin®'),
  ('Food & Restaurants', 'River Crab Blue Water Inn'),
  ('Food & Restaurants', 'Rubio’s Coastal Grill'),
  ('Food & Restaurants', 'Ruby Tuesday'),
  ('Food & Restaurants', 'Ruth’s Chris Steak House'),
  ('Food & Restaurants', 'Saltgrass Steak House'),
  ('Food & Restaurants', 'Schlotsky’s – Mix It Up®'),
  ('Food & Restaurants', 'Seasons 52®'),
  ('Food & Restaurants', 'Smashburger'),
  ('Food & Restaurants', 'Smoothie King'),
  ('Food & Restaurants', 'SONIC®'),
  ('Food & Restaurants', 'Starbucks'),
  ('Food & Restaurants', 'Steak ''n Shake®'),
  ('Food & Restaurants', 'Strip House'),
  ('Food & Restaurants', 'Subway®'),
  ('Food & Restaurants', 'sweetFrog®'),
  ('Food & Restaurants', 'Taco Bell®'),
  ('Food & Restaurants', 'Texas Roadhouse'),
  ('Food & Restaurants', 'TGI Fridays®'),
  ('Food & Restaurants', 'The Cheesecake Factory'),
  ('Food & Restaurants', 'The Coffee Bean & Tea Leaf®'),
  ('Food & Restaurants', 'The Oceanaire'),
  ('Food & Restaurants', 'Tower of the Americas'),
  ('Food & Restaurants', 'UNO Pizzeria & Grill®'),
  ('Food & Restaurants', 'Vic & Anthony’s'),
  ('Food & Restaurants', 'Village Inn'),
  ('Food & Restaurants', 'Willie G''s'),
  ('Food & Restaurants', 'Yard House®'),
  ('Food & Restaurants', 'Zaxby’s'),
  ('General Merchandise', 'Amazon'),
  ('General Merchandise', 'Sam''s Club'),
  ('General Merchandise', 'Target'),
  ('General Merchandise', 'The Engage2Reward™ Choice Card'),
  ('General Merchandise', 'Walmart'),
  ('General Merchandise', 'Walmart (Alcohol / Tobacco / Firearms Prohibited)'),
  ('General Merchandise', 'Walmart Healthy Living'),
  ('Home Furnishings & Improvement', 'Ace Hardware'),
  ('Home Furnishings & Improvement', 'Bed Bath & Beyond'),
  ('Home Furnishings & Improvement', 'Canvaspop'),
  ('Home Furnishings & Improvement', 'CB2'),
  ('Home Furnishings & Improvement', 'Cost Plus World Market®'),
  ('Home Furnishings & Improvement', 'Crate & Barrel'),
  ('Home Furnishings & Improvement', 'HomeGoods'),
  ('Home Furnishings & Improvement', 'IKEA'),
  ('Home Furnishings & Improvement', 'Lowe’s®'),
  ('Home Furnishings & Improvement', 'Menards®'),
  ('Home Furnishings & Improvement', 'Pottery Barn®'),
  ('Home Furnishings & Improvement', 'The Container Store'),
  ('Home Furnishings & Improvement', 'The Home Depot®'),
  ('Home Furnishings & Improvement', 'Wayfair'),
  ('Home Furnishings & Improvement', 'west elm®'),
  ('Home Furnishings & Improvement', 'Williams Sonoma®'),
  ('Pets', '1-800-PetSupplies.com'),
  ('Pets', 'BarkBox'),
  ('Pets', 'Chewy®'),
  ('Pets', 'Pets Choice Card'),
  ('Pets', 'Petco'),
  ('Pets', 'PetSmart'),
  ('Specialty Retail', 'Apple Gift Card'),
  ('Specialty Retail', 'Barnes & Noble'),
  ('Specialty Retail', 'Bath & Body Works'),
  ('Specialty Retail', 'Best Buy®'),
  ('Specialty Retail', 'eBay'),
  ('Specialty Retail', 'Etsy'),
  ('Specialty Retail', 'Fanatics'),
  ('Specialty Retail', 'Fruit Bouquets'),
  ('Specialty Retail', 'Groupon'),
  ('Specialty Retail', 'Guitar Center'),
  ('Specialty Retail', 'LUSH Fresh Handmade Cosmetics'),
  ('Specialty Retail', 'Michaels'),
  ('Specialty Retail', 'Office Depot® Office Max®'),
  ('Specialty Retail', 'Sephora'),
  ('Specialty Retail', 'Spa Week'),
  ('Specialty Retail', 'Staples'),
  ('Specialty Retail', 'The Vitamin Shoppe®'),
  ('Specialty Retail', 'Total Wine & More'),
  ('Specialty Retail', 'Tractor Supply Company'),
  ('Specialty Retail', 'Ulta'),
  ('Specialty Retail', 'Yankee Candle®'),
  ('Sporting Goods', 'Academy Sports + Outdoors'),
  ('Sporting Goods', 'Bass Pro Shops®'),
  ('Sporting Goods', 'Cabela’s®'),
  ('Sporting Goods', 'Callaway'),
  ('Sporting Goods', 'Columbia'),
  ('Sporting Goods', 'DICK''s Sporting Goods'),
  ('Sporting Goods', 'MLB Shop'),
  ('Sporting Goods', 'NASCAR.com'),
  ('Sporting Goods', 'NBA Store'),
  ('Sporting Goods', 'NFLShop.com'),
  ('Sporting Goods', 'NHL Shop'),
  ('Sporting Goods', 'PXG'),
  ('Sporting Goods', 'REI'),
  ('Sporting Goods', 'Sportsman’s Warehouse'),
  ('Travel & Entertainment', 'AirBnB'),
  ('Travel & Entertainment', 'Amtrak'),
  ('Travel & Entertainment', 'Best Western'),
  ('Travel & Entertainment', 'Carnival Cruise Lines'),
  ('Travel & Entertainment', 'Celebrity Cruises'),
  ('Travel & Entertainment', 'Delta Airlines'),
  ('Travel & Entertainment', 'Disney Parks/Stores'),
  ('Travel & Entertainment', 'Fairmont Hotels & Resorts'),
  ('Travel & Entertainment', 'Global Hotel Card Powered by Expedia'),
  ('Travel & Entertainment', 'Golden Nugget'),
  ('Travel & Entertainment', 'Holland America Line'),
  ('Travel & Entertainment', 'Hotels.com®'),
  ('Travel & Entertainment', 'Marriott'),
  ('Travel & Entertainment', 'Princess Cruise Lines'),
  ('Travel & Entertainment', 'Raffles Hotels & Resorts'),
  ('Travel & Entertainment', 'Royal Caribbean'),
  ('Travel & Entertainment', 'San Luis Resort'),
  ('Travel & Entertainment', 'Southwest® Airlines'),
  ('Travel & Entertainment', 'TripGift®'),
  ('Travel & Entertainment', 'Swissôtel Hotels & Resorts'),
  ('Travel & Entertainment', 'Turo'),
  ('Travel & Entertainment', 'Ube')
on conflict (provider_category, brand_name) do nothing;

commit;
