-- BASELINE MIGRATION — DO NOT EDIT TO ADD NEW CHANGES.
--
-- These three tables were created directly against the remote database
-- (dashboard SQL editor) before the Supabase CLI was ever used to push, so
-- they had no migration file. This file reconstructs their exact state as
-- introspected from project ocgdfnvvjvutevgqzzgj on 2026-08-15.
--
-- It is registered with `supabase migration repair --status applied` rather
-- than executed remotely: the objects already exist there. It DOES run on a
-- fresh local `supabase db reset`, which is the point — local and remote agree.
--
-- Any new change belongs in a later migration, never in here.

create table public.catalog_items (
  id uuid primary key default gen_random_uuid(),
  catalog_item_id text not null unique,
  name text not null,
  category text not null,
  brand_id text,
  retailer_id text,
  msrp integer,
  status text not null default 'draft',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint catalog_items_id_format_check
    check (catalog_item_id ~ '^itm_[0-9a-f]+$'),
  constraint catalog_items_status_check
    check (status in ('draft', 'active', 'featured', 'hidden', 'archived', 'discontinued'))
);

-- NOTE: catalog_items.updated_at has no maintenance trigger in the remote
-- database, so it currently never advances past insert time. Reproduced here
-- as-is; the trigger is added in 20260815170000.

create table public.health_check (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  message text
);

create table public.ledger_entries (
  id uuid primary key default gen_random_uuid(),
  ledger_entry_id text not null unique,
  customer_id uuid not null references public.customers (id) on delete cascade,
  entry_type text not null,
  balance_type text not null,
  amount integer not null,
  currency text not null default 'USD',
  source_event text not null,
  related_pool_id text,
  related_entry_id text,
  corrects_ledger_entry_id text,
  funding_ip_address text,
  funding_device_fingerprint text,
  created_at timestamptz not null default now(),
  constraint ledger_entries_entry_id_format_check
    check (ledger_entry_id ~ '^len_[0-9a-f]+$'),
  constraint ledger_entries_entry_type_check
    check (entry_type in ('DEPOSIT', 'ENTRY_DEBIT', 'REBATE_CREDIT', 'REFUND', 'PAYOUT', 'CORRECTION')),
  constraint ledger_entries_balance_type_check
    check (balance_type in ('PLAYABLE', 'REBATE')),
  constraint ledger_entries_amount_not_zero
    check (amount <> 0)
);

create index ledger_entries_customer_id_idx
  on public.ledger_entries (customer_id);

alter table public.catalog_items enable row level security;
alter table public.health_check enable row level security;
alter table public.ledger_entries enable row level security;

create policy "Anyone can view catalog items"
  on public.catalog_items
  for select
  to anon, authenticated
  using (true);

create policy "Customers can select own ledger entries"
  on public.ledger_entries
  for select
  to authenticated
  using (auth.uid() = customer_id);

-- health_check intentionally has RLS enabled and no policies or grants:
-- it is reachable only by service_role.

-- The ledger is append-only from the client's perspective: no insert, update,
-- or delete grant. Entries are written by server-side service_role paths.
grant select on public.catalog_items to anon, authenticated;
grant select on public.ledger_entries to authenticated;
